fix wol race condition (wait for hosts to boot)

diff --git a/.github/workflows/auto-deploy.yml b/.github/workflows/auto-deploy.yml
--- a/.github/workflows/auto-deploy.yml
+++ b/.github/workflows/auto-deploy.yml
@@ -49,6 +49,16 @@ jobs:
           echo "$HOSTS" | tr ' ' '\n' | \
           xargs -P 10 -n 1 -I {} \
           sh -c "
+            # wait for host to be online with a timeout of 5s per attempt and 12
+            # total tries, but fail immediately if the error is auth related
+            if ! ssh -o BatchMode=yes \
+                     -o ConnectTimeout=5 \
+                     -o ConnectionAttempts=12 \
+                     {} echo 'continuous deployment ping!'; then
+              echo '❌ Failed to deploy to {} (ssh timeout)'
+              echo 'FAILURE:{}' >> results.txt
+            fi
+
             if nix develop .#deploy -c colmena apply --on {} switch > {}.log 2>&1; then
               echo '✅ Successfully deployed to {}'
               echo 'SUCCESS:{}' >> results.txt
