github actions: move stuff around

diff --git a/.github/workflows/auto-deploy.yml b/.github/workflows/auto-deploy.yml
--- a/.github/workflows/auto-deploy.yml
+++ b/.github/workflows/auto-deploy.yml
@@ -18,15 +18,9 @@ jobs:
       - name: Setup hosts
         run: |
           HOSTS=$(nix eval .#autoDeploy.nodes --apply 'builtins.concatStringsSep " "' --raw)
-          echo "HOSTS=$HOSTS" >> $GITHUB_ENV
-
-      - name: Wake up hosts
-        run: |
           HOST_MACS=$(nix eval .#autoDeploy.MACs --apply 'builtins.concatStringsSep " "' --raw)
-          # not using quotes here so that each mac address is a separate argument
-          if ! nix develop .#deploy -c wol $HOST_MACS; then
-            echo '❌ Failed to wakeup nodes'
-          fi
+          echo "HOSTS=$HOSTS" >> $GITHUB_ENV
+          echo "HOST_MACS=$HOST_MACS" >> $GITHUB_ENV
 
       - name: Setup SSH
         run: |
@@ -43,6 +37,13 @@ jobs:
           StrictHostKeyChecking yes
           UpdateHostKeys no
           " >> ${{ github.workspace }}/ssh_config
+
+      - name: Wake up hosts
+        run: |
+          # not using quotes here so that each mac address is a separate argument
+          if ! nix develop .#deploy -c wol $HOST_MACS; then
+            echo '❌ Failed to wakeup nodes'
+          fi
 
       - name: Deploy with colmena
         env:
